# Generated by Django 5.0.6 on 2024-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recordtable_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtable',
            name='membership',
        ),
        migrations.AddField(
            model_name='recordtable',
            name='city',
            field=models.CharField(default='Islamabad', max_length=50),
        ),
    ]
